//
// Created by adadu on 2022/11/26.
//

#ifndef BRAINPYLIB_KERNEL_HELPERS_CONSTANT_CUH
#define BRAINPYLIB_KERNEL_HELPERS_CONSTANT_CUH


#define FULL_WARP_MASK 0xFFFFFFFF


#endif //BRAINPYLIB_KERNEL_HELPERS_CONSTANT_CUH
