name: Publish Linux wheel to PyPI.org
on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pypi:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.7'
            pep-425-tag: 'cp37-cp37m'
          - python-version: '3.8'
            pep-425-tag: 'cp38-cp38'
          - python-version: '3.9'
            pep-425-tag: 'cp39-cp39'
          - python-version: '3.10'
            pep-425-tag: 'cp310-cp310'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Checkout brainpy dummy project
#        uses: actions/checkout@v2
#        with:
#          repository: ztqakita/brainpylib
#          ref: main
#          path: brainpylib
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install twine auditwheel patchelf>=0.14
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
        with:
          python-versions: ${{ matrix.pep-425-tag }}
          build-requirements: 'setuptools cython numpy pybind11 numpy jax jaxlib'
          package-path: 'brainpylib'
      - name: Repair wheel
        run: |
          auditwheel repair --plat manylinux2014_x86_64 brainpylib/dist/*.whl
#      - name: Publish package
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}