name: Publish Windows wheel to PyPI.org
on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pypi:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.7'
            pep-425-tag: 'cp37-cp37m'
          - python-version: '3.8'
            pep-425-tag: 'cp38-cp38'
          - python-version: '3.9'
            pep-425-tag: 'cp39-cp39'
          - python-version: '3.10'
            pep-425-tag: 'cp310-cp310'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install numpy>=1.21.0
          python -m pip install "jaxlib==0.3.14" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
          python -m pip install https://github.com/google/jax/archive/refs/tags/jax-v0.3.14.tar.gz
          python -m pip install -r requirements-test.txt
          python -m pip install -r requirements.txt
          python -m pip install twine delvewheel pybind11 wheel
      - name: Add windows dll
        run: |
          if( '${{ matrix.python-version }}' == '3.10'){
            mkdir "build/lib.win-amd64-cpython-310/brainpylib"
            cp win_dll/*  build/lib.win-amd64-cpython-310/brainpylib
          }
          else{
            mkdir "build/lib.win-amd64-${{ matrix.python-version }}/brainpylib"
            cp win_dll/*  build/lib.win-amd64-${{ matrix.python-version }}/brainpylib
          }
#      - name:
#      - name: Build windows wheel
#        run: |
#          python setup.py bdist_wheel
#      - name: Publish wheels to PyPI
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#        run: |
#          twine upload dist\brainpylib*.whl
#      - name: Test brainpylib
#        run: |
#          python -m pip install dist\brainpylib-0.1.0-${{ matrix.pep-425-tag }}-win_amd64.whl
#          pytest brainpylib\